# Generated by Django 4.2.15 on 2025-09-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parceironegocio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='parceironegocio',
            name='contabilidade',
        ),
        migrations.RemoveField(
            model_name='parceironegocio',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='HistoricalParceiroNegocio',
        ),
        migrations.DeleteModel(
            name='ParceiroNegocio',
        ),
    ]
