# Generated by Django 5.2.5 on 2025-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('pessoas', '0002_alter_parceironegocio_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pessoafisica',
            name='pessoas_fis_contabi_382ac9_idx',
        ),
        migrations.RemoveIndex(
            model_name='pessoajuridica',
            name='pessoas_jur_contabi_0024f5_idx',
        ),
        migrations.AlterUniqueTogether(
            name='pessoafisica',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pessoajuridica',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalpessoafisica',
            name='contabilidade',
        ),
        migrations.RemoveField(
            model_name='historicalpessoajuridica',
            name='contabilidade',
        ),
        migrations.AlterField(
            model_name='historicalpessoafisica',
            name='cpf',
            field=models.CharField(db_index=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='historicalpessoajuridica',
            name='cnpj',
            field=models.CharField(db_index=True, max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('contabilidade', 'id_legado'), ('content_type', 'object_id')},
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='contabilidade',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='contabilidade',
        ),
    ]
