# Generated by Django 5.2.5 on 2025-09-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pessoas', '0004_alter_contrato_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('contabilidade', 'id_legado')},
        ),
    ]
