# Generated by Django 5.2.5 on 2025-09-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_remove_notafiscal_fiscal_nota_contabi_4e262b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotafiscalitem',
            name='sequencial_item',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequencial do Item no Legado'),
        ),
        migrations.AddField(
            model_name='notafiscalitem',
            name='sequencial_item',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequencial do Item no Legado'),
        ),
        migrations.AlterUniqueTogether(
            name='notafiscalitem',
            unique_together={('nota_fiscal', 'sequencial_item')},
        ),
    ]
