# Generated by Django 5.2.5 on 2025-09-23 20:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(db_index=True, help_text='ID do usuário no sistema legado (i_usuario) - ÚNICO GLOBAL', max_length=50, unique=True)),
                ('nome_usuario', models.CharField(db_index=True, help_text='Nome do usuário no sistema legado', max_length=100)),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Se o usuário está ativo no sistema')),
                ('data_ultimo_acesso', models.DateTimeField(blank=True, db_index=True, help_text='Data do último acesso ao sistema', null=True)),
                ('tipo_usuario', models.CharField(db_index=True, default='NORMAL', help_text='Tipo do usuário (GERENTE, EXTERNO, NORMAL, etc.)', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'indexes': [models.Index(fields=['ativo'], name='administrac_ativo_1437fc_idx'), models.Index(fields=['nome_usuario'], name='administrac_nome_us_37216b_idx'), models.Index(fields=['tipo_usuario'], name='administrac_tipo_us_029f7c_idx'), models.Index(fields=['ativo', 'data_ultimo_acesso'], name='administrac_ativo_ca1bef_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_acesso', models.DateTimeField(db_index=True, help_text='Data e hora do acesso')),
                ('tempo_sessao', models.DurationField(blank=True, help_text='Tempo de duração da sessão', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent do navegador', null=True)),
                ('modulo_acessado', models.CharField(blank=True, db_index=True, help_text='Módulo que foi acessado', max_length=100, null=True)),
                ('acao_realizada', models.CharField(blank=True, help_text='Ação realizada pelo usuário', max_length=200, null=True)),
                ('contabilidade', models.ForeignKey(help_text='Contabilidade responsável pelos dados', on_delete=django.db.models.deletion.CASCADE, to='core.contabilidade')),
                ('usuario', models.ForeignKey(help_text='Usuário que fez o acesso', on_delete=django.db.models.deletion.CASCADE, to='administracao.usuario')),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'indexes': [models.Index(fields=['contabilidade', 'usuario', 'data_acesso'], name='administrac_contabi_20a4a0_idx'), models.Index(fields=['contabilidade', 'data_acesso'], name='administrac_contabi_715459_idx'), models.Index(fields=['usuario', 'data_acesso'], name='administrac_usuario_d7c5b3_idx'), models.Index(fields=['data_acesso', 'modulo_acessado'], name='administrac_data_ac_cacc02_idx')],
            },
        ),
        migrations.CreateModel(
            name='LancamentoUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_lancamento', models.DateTimeField(db_index=True, help_text='Data e hora do lançamento')),
                ('tipo_operacao', models.CharField(db_index=True, help_text='Tipo da operação realizada', max_length=50)),
                ('descricao', models.TextField(help_text='Descrição do lançamento')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor do lançamento (se aplicável)', max_digits=15, null=True)),
                ('id_legado', models.CharField(db_index=True, help_text='ID do lançamento no sistema legado', max_length=100, unique=True)),
                ('modulo_origem', models.CharField(blank=True, db_index=True, help_text='Módulo de origem do lançamento', max_length=100, null=True)),
                ('status', models.CharField(db_index=True, default='ATIVO', help_text='Status do lançamento', max_length=20)),
                ('contabilidade', models.ForeignKey(help_text='Contabilidade responsável pelos dados', on_delete=django.db.models.deletion.CASCADE, to='core.contabilidade')),
                ('usuario', models.ForeignKey(help_text='Usuário que realizou o lançamento', on_delete=django.db.models.deletion.CASCADE, to='administracao.usuario')),
            ],
            options={
                'verbose_name': 'Lançamento do Usuário',
                'verbose_name_plural': 'Lançamentos dos Usuários',
                'indexes': [models.Index(fields=['contabilidade', 'usuario', 'data_lancamento'], name='administrac_contabi_aa44a2_idx'), models.Index(fields=['contabilidade', 'tipo_operacao', 'data_lancamento'], name='administrac_contabi_b089dd_idx'), models.Index(fields=['usuario', 'data_lancamento'], name='administrac_usuario_492d11_idx'), models.Index(fields=['data_lancamento', 'status'], name='administrac_data_la_d13bb2_idx'), models.Index(fields=['modulo_origem', 'data_lancamento'], name='administrac_modulo__bc9f8e_idx')],
                'unique_together': {('contabilidade', 'id_legado')},
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('acao', models.CharField(db_index=True, help_text='Tipo de ação realizada', max_length=50)),
                ('tabela_afetada', models.CharField(db_index=True, help_text='Tabela que foi afetada', max_length=100)),
                ('registro_id', models.CharField(help_text='ID do registro afetado', max_length=100)),
                ('dados_anteriores', models.JSONField(blank=True, help_text='Dados antes da alteração', null=True)),
                ('dados_novos', models.JSONField(blank=True, help_text='Dados após a alteração', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário', null=True)),
                ('contabilidade', models.ForeignKey(help_text='Contabilidade responsável pelos dados', on_delete=django.db.models.deletion.CASCADE, to='core.contabilidade')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que realizou a operação', null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracao.usuario')),
            ],
            options={
                'verbose_name': 'Auditoria do Sistema',
                'verbose_name_plural': 'Auditorias do Sistema',
                'indexes': [models.Index(fields=['contabilidade', 'usuario', 'data_criacao'], name='administrac_contabi_11284a_idx'), models.Index(fields=['contabilidade', 'acao', 'data_criacao'], name='administrac_contabi_a07986_idx'), models.Index(fields=['tabela_afetada', 'data_criacao'], name='administrac_tabela__ac15a5_idx'), models.Index(fields=['data_criacao'], name='administrac_data_cr_f35dfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioContabilidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa_cnpj', models.CharField(db_index=True, help_text='CNPJ da empresa que o usuário acessa', max_length=20)),
                ('empresa_nome', models.CharField(help_text='Nome da empresa que o usuário acessa', max_length=200)),
                ('data_inicio', models.DateField(db_index=True, help_text='Data de início do contrato')),
                ('data_fim', models.DateField(blank=True, db_index=True, help_text='Data de fim do contrato (NULL = ativo)', null=True)),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Se o vínculo está ativo')),
                ('modulos_acesso', models.JSONField(default=list, help_text='Lista de módulos que o usuário pode acessar')),
                ('contabilidade', models.ForeignKey(help_text='Contabilidade responsável pelos dados', on_delete=django.db.models.deletion.CASCADE, to='core.contabilidade')),
                ('usuario', models.ForeignKey(help_text='Usuário que tem acesso à contabilidade', on_delete=django.db.models.deletion.CASCADE, to='administracao.usuario')),
            ],
            options={
                'verbose_name': 'Vínculo Usuário-Contabilidade',
                'verbose_name_plural': 'Vínculos Usuário-Contabilidade',
                'indexes': [models.Index(fields=['contabilidade', 'usuario', 'data_inicio'], name='administrac_contabi_a57b3d_idx'), models.Index(fields=['contabilidade', 'ativo', 'data_inicio'], name='administrac_contabi_32ed25_idx'), models.Index(fields=['usuario', 'ativo', 'data_inicio'], name='administrac_usuario_18979c_idx'), models.Index(fields=['empresa_cnpj', 'ativo'], name='administrac_empresa_0c0fc9_idx'), models.Index(fields=['data_inicio', 'data_fim'], name='administrac_data_in_2ed164_idx')],
                'unique_together': {('contabilidade', 'usuario', 'empresa_cnpj')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('modulo_id', models.IntegerField(db_index=True, help_text='ID do módulo no sistema legado (ROW_NUM)')),
                ('modulo_nome', models.CharField(help_text='Nome do módulo', max_length=100)),
                ('ativo', models.BooleanField(db_index=True, default=True, help_text='Se o módulo está ativo para o usuário')),
                ('contabilidade', models.ForeignKey(help_text='Contabilidade responsável pelos dados', on_delete=django.db.models.deletion.CASCADE, to='core.contabilidade')),
                ('usuario', models.ForeignKey(help_text='Usuário que tem acesso ao módulo', on_delete=django.db.models.deletion.CASCADE, to='administracao.usuario')),
            ],
            options={
                'verbose_name': 'Módulo do Usuário',
                'verbose_name_plural': 'Módulos dos Usuários',
                'indexes': [models.Index(fields=['contabilidade', 'usuario', 'modulo_id'], name='administrac_contabi_158f2a_idx'), models.Index(fields=['contabilidade', 'modulo_id', 'ativo'], name='administrac_contabi_d6620d_idx'), models.Index(fields=['usuario', 'ativo'], name='administrac_usuario_a62d15_idx')],
                'unique_together': {('contabilidade', 'usuario', 'modulo_id')},
            },
        ),
    ]
