# Generated by Django 5.2.5 on 2025-09-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
    ]
