# Generated by Django 4.2.15 on 2025-09-17 15:11

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLancamentoContabil',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('numero_lancamento', models.CharField(max_length=50, verbose_name='Número do Lançamento')),
                ('data_lancamento', models.DateField(verbose_name='Data do Lançamento')),
                ('historico', models.TextField(verbose_name='Histórico')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Lançamento Contábil',
                'verbose_name_plural': 'historical Lançamentos Contábeis',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPartida',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Partida',
                'verbose_name_plural': 'historical Partidas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPlanoContas',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('id_legado', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nivel', models.IntegerField(verbose_name='Nível')),
                ('aceita_lancamento', models.BooleanField(default=True, verbose_name='Aceita Lançamento')),
                ('tipo_conta', models.CharField(max_length=20, verbose_name='Tipo de Conta')),
                ('natureza', models.CharField(max_length=10, verbose_name='Natureza')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Plano de Conta',
                'verbose_name_plural': 'historical Planos de Contas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lancamento', models.CharField(max_length=50, verbose_name='Número do Lançamento')),
                ('data_lancamento', models.DateField(verbose_name='Data do Lançamento')),
                ('historico', models.TextField(verbose_name='Histórico')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
            ],
            options={
                'verbose_name': 'Lançamento Contábil',
                'verbose_name_plural': 'Lançamentos Contábeis',
                'db_table': 'contabil_lancamentos',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'contabil_partidas',
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nivel', models.IntegerField(verbose_name='Nível')),
                ('aceita_lancamento', models.BooleanField(default=True, verbose_name='Aceita Lançamento')),
                ('tipo_conta', models.CharField(max_length=20, verbose_name='Tipo de Conta')),
                ('natureza', models.CharField(max_length=10, verbose_name='Natureza')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_filhas', to='contabil.planocontas')),
            ],
            options={
                'verbose_name': 'Plano de Conta',
                'verbose_name_plural': 'Planos de Contas',
                'db_table': 'contabil_plano_contas',
            },
        ),
    ]
