# Generated by Django 4.2.15 on 2025-09-17 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabil', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontas',
            name='contabilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_contas', to='core.contabilidade'),
        ),
        migrations.AddField(
            model_name='partida',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabil.planocontas'),
        ),
        migrations.AddField(
            model_name='partida',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabil.lancamentocontabil'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='contabilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_contabeis', to='core.contabilidade'),
        ),
        migrations.AddField(
            model_name='historicalplanocontas',
            name='conta_pai',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabil.planocontas'),
        ),
        migrations.AddField(
            model_name='historicalplanocontas',
            name='contabilidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contabilidade'),
        ),
        migrations.AddField(
            model_name='historicalplanocontas',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpartida',
            name='conta',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabil.planocontas'),
        ),
        migrations.AddField(
            model_name='historicalpartida',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpartida',
            name='lancamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contabil.lancamentocontabil'),
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='contabilidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contabilidade'),
        ),
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='planocontas',
            unique_together={('contabilidade', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='lancamentocontabil',
            index=models.Index(fields=['contabilidade', 'data_lancamento'], name='contabil_la_contabi_de1507_idx'),
        ),
    ]
