# Generated by Django 5.2.5 on 2025-09-22 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('pessoas', '0005_alter_contrato_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado')),
                ('nome', models.CharField(max_length=255)),
                ('cbo_2002', models.CharField(blank=True, max_length=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabilidade')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoajuridica')),
            ],
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabilidade')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoajuridica')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado')),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabilidade')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoajuridica')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabilidade')),
                ('pessoa_fisica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoas.pessoafisica')),
            ],
            options={
                'unique_together': {('contabilidade', 'pessoa_fisica', 'id_legado')},
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('P', 'Provento'), ('D', 'Desconto'), ('B', 'Base')], max_length=1)),
                ('incide_inss', models.BooleanField(default=False)),
                ('incide_irrf', models.BooleanField(default=False)),
                ('incide_fgts', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabilidade')),
            ],
            options={
                'unique_together': {('contabilidade', 'id_legado')},
            },
        ),
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabilidade')),
            ],
        ),
        migrations.CreateModel(
            name='ConvencaoColetiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabilidade')),
                ('sindicato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.sindicato')),
            ],
        ),
        migrations.CreateModel(
            name='VinculoEmpregaticio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(null=True)),
                ('matricula', models.CharField(max_length=20)),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ativo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.cargo')),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.contabilidade')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.departamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Rescisao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_rescisao', models.DateField()),
                ('motivo_codigo', models.CharField(max_length=10)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proventos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descontos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fgts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('aviso_previo', models.CharField(blank=True, max_length=20, null=True)),
                ('data_aviso', models.DateField(blank=True, null=True)),
                ('aviso_indenizado', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_legado', models.CharField(blank=True, max_length=50, null=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rescisoes', to='core.contabilidade')),
                ('vinculo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rescisao', to='funcionarios.vinculoempregaticio')),
            ],
            options={
                'verbose_name': 'Rescisão',
                'verbose_name_plural': 'Rescisões',
                'unique_together': {('contabilidade', 'vinculo')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoAquisitivoFerias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(max_length=50, verbose_name='ID Legado')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('dias_direito', models.IntegerField(default=30)),
                ('situacao', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('P', 'Programado')], default='A', max_length=1)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos_aquisitivos', to='funcionarios.vinculoempregaticio')),
            ],
            options={
                'unique_together': {('vinculo', 'id_legado')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoSalario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salario_novo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_mudanca', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_salarios', to='funcionarios.vinculoempregaticio')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_mudanca', models.DateField()),
                ('cargo_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.cargo')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_cargos', to='funcionarios.vinculoempregaticio')),
            ],
        ),
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo_aquisitivo_inicio', models.DateField()),
                ('periodo_aquisitivo_fim', models.DateField()),
                ('data_inicio_gozo', models.DateField()),
                ('dias_gozo', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ferias', to='funcionarios.vinculoempregaticio')),
            ],
        ),
        migrations.CreateModel(
            name='GozoFerias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(max_length=255)),
                ('data_inicio_gozo', models.DateField(blank=True, null=True)),
                ('data_fim_gozo', models.DateField(blank=True, null=True)),
                ('dias_gozo', models.IntegerField(default=0)),
                ('dias_abono', models.IntegerField(default=0)),
                ('valor_ferias', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_abono', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('periodo_aquisitivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gozos', to='funcionarios.periodoaquisitivoferias')),
            ],
            options={
                'verbose_name': 'Gozo de Férias',
                'verbose_name_plural': 'Gozos de Férias',
                'unique_together': {('periodo_aquisitivo', 'id_legado')},
            },
        ),
        migrations.CreateModel(
            name='RescisaoRubrica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('P', 'Provento'), ('D', 'Desconto'), ('B', 'Base')], max_length=1)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rescisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='funcionarios.rescisao')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='funcionarios.rubrica')),
            ],
            options={
                'verbose_name': 'Rubrica de Rescisão',
                'verbose_name_plural': 'Rubricas de Rescisão',
                'unique_together': {('rescisao', 'rubrica', 'tipo', 'descricao')},
            },
        ),
        migrations.CreateModel(
            name='Afastamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_legado', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('previsao_fim', models.DateField(blank=True, null=True)),
                ('dias_afastado', models.IntegerField(default=0, help_text='Número de dias do afastamento.')),
                ('motivo_afastamento', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_doenca', models.CharField(blank=True, help_text='CID', max_length=50, null=True)),
                ('nome_medico', models.CharField(blank=True, max_length=255, null=True)),
                ('crm_medico', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='core.contabilidade')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afastamentos', to='funcionarios.vinculoempregaticio')),
            ],
            options={
                'verbose_name': 'Afastamento',
                'verbose_name_plural': 'Afastamentos',
                'ordering': ['-data_inicio'],
                'unique_together': {('contabilidade', 'vinculo', 'id_legado')},
            },
        ),
    ]
