# Generated by Django 4.2.15 on 2025-09-17 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNAE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código CNAE')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'CNAE',
                'verbose_name_plural': 'CNAEs',
                'db_table': 'cadastros_gerais_cnae',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='cadastros_g_codigo_7fb2fc_idx')],
            },
        ),
    ]
