# Generated by Django 5.2.5 on 2025-09-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabil', '0002_initial'),
        ('pessoas', '0007_alter_quadrosocietario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallancamentocontabil',
            name='contrato',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.contrato'),
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_contabeis', to='pessoas.contrato'),
        ),
    ]
