# Generated by Django 5.2.5 on 2025-09-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('pessoas', '0003_remove_pessoafisica_pessoas_fis_contabi_382ac9_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('contabilidade', 'content_type', 'object_id'), ('contabilidade', 'id_legado')},
        ),
    ]
