# Generated by Django 5.2.5 on 2025-09-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_alter_contrato_unique_together'),
        ('pessoas', '0005_quadro_societario'),
    ]

    operations = [
    ]
