# Generated by Django 5.2.5 on 2025-09-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_merge_20250924_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quadrosocietario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quadrosocietario',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='quadrosocietario',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='CapitalSocial',
        ),
        migrations.DeleteModel(
            name='QuadroSocietario',
        ),
    ]
