# Generated by Django 5.2.5 on 2025-09-24 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_alter_quadrosocietario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('1', 'Simples Nacional'), ('2', 'Lucro Presumido'), ('3', 'Lucro Real'), ('4', 'MEI - Microempreendedor Individual')], max_length=1, null=True, verbose_name='Regime Tributário'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='simples_nacional',
            field=models.BooleanField(default=False, verbose_name='Simples Nacional'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('1', 'Simples Nacional'), ('2', 'Lucro Presumido'), ('3', 'Lucro Real'), ('4', 'MEI - Microempreendedor Individual')], max_length=1, null=True, verbose_name='Regime Tributário'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='simples_nacional',
            field=models.BooleanField(default=False, verbose_name='Simples Nacional'),
        ),
    ]
