# Generated by Django 5.2.5 on 2025-09-24 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pessoas', '0008_historicalpessoajuridica_regime_tributario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalSocial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_capital', models.DecimalField(decimal_places=2, help_text='Valor do capital social', max_digits=15)),
                ('data_referencia', models.DateField(db_index=True, help_text='Data de referência do capital social')),
                ('fonte', models.CharField(default='QUADRO_SOCIETARIO', help_text='Fonte dos dados (QUADRO_SOCIETARIO, CONTRATO, etc.)', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Empresa do capital social', on_delete=django.db.models.deletion.CASCADE, related_name='capital_social_historico', to='pessoas.pessoajuridica')),
            ],
            options={
                'verbose_name': 'Capital Social',
                'verbose_name_plural': 'Capitais Sociais',
                'ordering': ['-data_referencia'],
                'indexes': [models.Index(fields=['empresa', 'data_referencia'], name='pessoas_cap_empresa_860757_idx'), models.Index(fields=['data_referencia'], name='pessoas_cap_data_re_020109_idx'), models.Index(fields=['fonte'], name='pessoas_cap_fonte_97fe88_idx')],
                'unique_together': {('empresa', 'data_referencia', 'fonte')},
            },
        ),
        migrations.CreateModel(
            name='QuadroSocietario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='ID do sócio')),
                ('participacao_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de participação do sócio', max_digits=5, null=True)),
                ('quantidade_quotas', models.IntegerField(blank=True, help_text='Quantidade de quotas do sócio', null=True)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, help_text='Capital social da empresa', max_digits=15, null=True)),
                ('id_legado_socio', models.CharField(blank=True, db_index=True, help_text='ID do sócio no sistema legado', max_length=50, null=True)),
                ('id_legado_empresa', models.CharField(blank=True, db_index=True, help_text='ID da empresa no sistema legado', max_length=50, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('content_type', models.ForeignKey(help_text='Tipo do sócio (PessoaFisica ou PessoaJuridica)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('empresa', models.ForeignKey(help_text='Empresa do quadro societário', on_delete=django.db.models.deletion.CASCADE, related_name='quadro_societario', to='pessoas.pessoajuridica')),
            ],
            options={
                'verbose_name': 'Quadro Societário',
                'verbose_name_plural': 'Quadros Societários',
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='pessoas_qua_empresa_7ad8c4_idx'), models.Index(fields=['content_type', 'object_id'], name='pessoas_qua_content_3240d6_idx'), models.Index(fields=['id_legado_empresa', 'id_legado_socio'], name='pessoas_qua_id_lega_8a7e21_idx'), models.Index(fields=['data_criacao'], name='pessoas_qua_data_cr_bc98fe_idx')],
                'unique_together': {('empresa', 'content_type', 'object_id')},
            },
        ),
    ]
