# Generated by Django 5.2.5 on 2025-09-17 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('fiscal', '0001_initial'),
        ('pessoas', '0002_alter_parceironegocio_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notafiscal',
            name='apenas_um_parceiro_nao_nulo',
        ),
        migrations.RemoveIndex(
            model_name='notafiscal',
            name='fiscal_nota_contabi_e635ae_idx',
        ),
        migrations.AlterUniqueTogether(
            name='notafiscal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalnotafiscal',
            name='id_legado_cli_for',
        ),
        migrations.RemoveField(
            model_name='historicalnotafiscal',
            name='id_legado_empresa',
        ),
        migrations.RemoveField(
            model_name='historicalnotafiscal',
            name='parceiro_pf',
        ),
        migrations.RemoveField(
            model_name='historicalnotafiscal',
            name='parceiro_pj',
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='content_type_parceiro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='A empresa (cliente da contabilidade) a quem esta nota pertence.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='id_legado_nota',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado da Nota'),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='object_id_parceiro',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='content_type_parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais_parceiro', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='empresa',
            field=models.ForeignKey(help_text='A empresa (cliente da contabilidade) a quem esta nota pertence.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minhas_notas_fiscais', to='pessoas.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='id_legado_nota',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado da Nota'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='object_id_parceiro',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['contabilidade', 'empresa'], name='fiscal_nota_contabi_4e262b_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['content_type_parceiro', 'object_id_parceiro'], name='fiscal_nota_content_7f0268_idx'),
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='id_legado_cli_for',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='id_legado_empresa',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='parceiro_pf',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='parceiro_pj',
        ),
    ]
