# Generated by Django 5.2.5 on 2025-09-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('fiscal', '0002_remove_notafiscal_apenas_um_parceiro_nao_nulo_and_more'),
        ('pessoas', '0003_remove_pessoafisica_pessoas_fis_contabi_382ac9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notafiscal',
            name='fiscal_nota_contabi_4e262b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notafiscal',
            name='fiscal_nota_content_7f0268_idx',
        ),
        migrations.RemoveField(
            model_name='historicalnotafiscal',
            name='content_type_parceiro',
        ),
        migrations.RemoveField(
            model_name='historicalnotafiscal',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='historicalnotafiscal',
            name='object_id_parceiro',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='content_type_parceiro',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='object_id_parceiro',
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='id_legado_cli_for',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado Cliente/Fornecedor'),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='id_legado_empresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado da Empresa'),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='parceiro_pf',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.pessoafisica'),
        ),
        migrations.AddField(
            model_name='historicalnotafiscal',
            name='parceiro_pj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pessoas.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='id_legado_cli_for',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado Cliente/Fornecedor'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='id_legado_empresa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Legado da Empresa'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='parceiro_pf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='pessoas.pessoafisica'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='parceiro_pj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='pessoas.pessoajuridica'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['contabilidade', 'parceiro_pj'], name='fiscal_nota_contabi_f68e05_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['contabilidade', 'parceiro_pf'], name='fiscal_nota_contabi_4128b9_idx'),
        ),
        migrations.AddIndex(
            model_name='notafiscal',
            index=models.Index(fields=['chave_acesso'], name='fiscal_nota_chave_a_1bfb61_idx'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.CheckConstraint(condition=models.Q(('parceiro_pj__isnull', False), ('parceiro_pf__isnull', False), _connector='OR'), name='fiscal_notafiscal_tem_parceiro'),
        ),
        migrations.AddConstraint(
            model_name='notafiscal',
            constraint=models.CheckConstraint(condition=models.Q(('parceiro_pj__isnull', False), ('parceiro_pf__isnull', False), _negated=True), name='fiscal_notafiscal_apenas_um_parceiro'),
        ),
    ]
